## Assignment 2 | Data types

### 1. Working with Lists

Identify (with code, not manually) and print the list in the following list (G) whose sum of its elements is the highest. 

G = [[13,9,8], [14,6,12], [10,13,11], [7,18,9]]



In [26]:
G = [[13,9,8], [14,6,12], [10,13,11], [7,18,9]]

sum(G[0])

30

### 2. Create and Query a Dictionary on State Demographics

Based on the following table create two dictionaries, one for California and one for New York state. Each dictionary should have the following keys / value-type: name: (string) , population density: (float), race (dict), tenure: (dict). 

1.  Create an outer dictionary called "states" that each contain dictionaries containing name, pop_density, race as a dictionary, and tenure. 

1.  Check if texas is in our state dictionary (we know it isn't but show us).

1. Print the race distribution for New York as percentages with 2 decimal places

1. Print the state name, the tenure category, and the percentage of households of that tenure in each state, with two decimal places

![Census.jpg](Census.jpg)


In [220]:
#Solution to 1:

CA={'name':'California', 'pop_density': 239.1,\
    'race': {'white': 0.57, 'african_american': 0.06, 'asian': 0.13, 'other': 0.22},\
    'tenure': {'owner': 7035371,'renter':5542127 }}
NY={'name':'New York', 'pop_density': 411.2,\
    'race': {'white': 0.65, 'african_american': 0.15, 'asian': 0.07, 'other': 0.22},\
    'tenure': {'owner': 3897837,'renter':3419918}}

    

In [106]:
states = {}
states["CA"] = CA
states["NY"] = NY
states

{'CA': {'name': 'California',
  'pop_density': 239.1,
  'race': {'african_american': 0.06,
   'asian': 0.13,
   'other': 0.22,
   'white': 0.57},
  'tenure': {'owner': 7035371, 'renter': 5542127}},
 'NY': {'name': 'New York',
  'pop_density': 411.2,
  'race': {'african_american': 0.15,
   'asian': 0.07,
   'other': 0.22,
   'white': 0.65},
  'tenure': {'owner': 3897837, 'renter': 3419918}}}

In [221]:
# Solution to 2
'Texas' in states

False

In [222]:
# Solution to 3
for i in states["NY"]["race"].keys():
    print(i, str(round(100 * race[i],2))+'%')

white 65.0%
african_american 15.0%
asian 7.0%
other 22.0%


In [223]:
# Solution to 4
for i in states.values():
    print(i["name"], '\n', 'owner:', str(round(100* i["tenure"]["owner"]/(i["tenure"]["owner"]+i["tenure"]["renter"]),2))+'%',\
         '\n', 'renter:', str(round(100 * i["tenure"]["renter"]/(i["tenure"]["owner"]+i["tenure"]["renter"]),2))+'%')

California 
 owner: 55.94% 
 renter: 44.06%
New York 
 owner: 53.27% 
 renter: 46.73%


### 3. Working with Numpy Arrays

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
a = np.ones(100).reshape(10,10)*3
a

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]])

In [13]:
b = np.random.uniform(0,1,100).reshape(10,10)
b

array([[ 0.7053364 ,  0.69212851,  0.52099591,  0.12662091,  0.80383873,
         0.72521233,  0.04241316,  0.88256179,  0.37951943,  0.7072789 ],
       [ 0.13822292,  0.81438051,  0.9331823 ,  0.27405526,  0.55514774,
         0.25645046,  0.69494015,  0.74865781,  0.99205391,  0.48686679],
       [ 0.7212531 ,  0.60003724,  0.14531165,  0.27219301,  0.88887615,
         0.59007147,  0.20491565,  0.68382761,  0.85161679,  0.8628242 ],
       [ 0.31447589,  0.16640822,  0.03243917,  0.53719061,  0.68690196,
         0.16669175,  0.88944444,  0.24474502,  0.79625103,  0.242206  ],
       [ 0.60958581,  0.53004003,  0.78609278,  0.93239401,  0.21125376,
         0.38861239,  0.20046715,  0.21310081,  0.7694347 ,  0.29924009],
       [ 0.74220298,  0.0411803 ,  0.54949707,  0.77021417,  0.47293409,
         0.24955085,  0.53080466,  0.81876875,  0.97645888,  0.27117325],
       [ 0.53305151,  0.19447217,  0.96413459,  0.24263079,  0.29362186,
         0.10948171,  0.95273359,  0.63427075

In [16]:
c = a/b
c

array([[   4.25328964,    4.33445517,    5.75820262,   23.69276975,
           3.73209191,    4.13671953,   70.73276906,    3.39919542,
           7.90473359,    4.24160823],
       [  21.70407065,    3.68378167,    3.21480593,   10.94669726,
           5.40396689,   11.698166  ,    4.31691853,    4.00717118,
           3.02402922,    6.16184967],
       [   4.15942751,    4.99968966,   20.64528192,   11.02159107,
           3.37504838,    5.0841299 ,   14.64017011,    4.38707062,
           3.52271118,    3.47695393],
       [   9.53968191,   18.02795613,   92.48078268,    5.58460993,
           4.36743549,   17.99729187,    3.37289197,   12.25765505,
           3.76765602,   12.38615074],
       [   4.92137441,    5.65994986,    3.81634343,    3.2175239 ,
          14.20093055,    7.7197745 ,   14.96504552,   14.07784428,
           3.89896633,   10.02539476],
       [   4.04202096,   72.85037429,    5.4595378 ,    3.89502054,
           6.34337863,   12.02159796,    5.65179663,    3

In [24]:
np.percentile(c,[5,10,25,50,75,90,95])

array([  3.1315039 ,   3.35735516,   3.87989637,   5.57505759,
        12.66105514,  24.46593497,  70.83864932])